---
abstract: unknown
author:
  - 'MaximusFox <shok@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Gyazo
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request::Common: 0
  LWP::Protocol::socks: 0
  LWP::UserAgent: 0
  URI::Simple: 0
  perl: 5.008008
resources:
  bugtracker: https://github.com/maximusfox/WebService--Gyazo/issues
  homepage: https://github.com/maximusfox/WebService--Gyazo
  license: http://dev.perl.org/licenses/
  repository: https://github.com/maximusfox/WebService--Gyazo
version: 0.01
